# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       libvisual

# >> macros
# << macros

Summary:    Abstraction library for audio visualisation plugins
Version:    0.4.0
Release:    1
Group:      Applications/Multimedia
License:    LGPLv2+
URL:        http://github.com/Libvisual/libvisual
Source0:    http://dl.sf.net/libvisual/libvisual-0.4.0.tar.gz
Source100:  libvisual.yaml
Patch0:     libvisual-0.4.0-fixes.patch
Patch1:     libvisual-0.4.0-compiler_warnings.patch
Patch2:     libvisual-0.4.0-unref-static.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xproto)

%description
Audio visualization framework

%package devel
Summary:    Development components for the libvisual library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Audio visualization framework (development package)


%prep
%setup -q -n %{name}-%{version}

# libvisual-0.4.0-fixes.patch
%patch0 -p1
# libvisual-0.4.0-compiler_warnings.patch
%patch1 -p1
# libvisual-0.4.0-unref-static.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%find_lang libvisual-0.4

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files -f libvisual-0.4.lang
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_libdir}/*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc README NEWS TODO AUTHORS
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
%{_includedir}/*
# << files devel
